clear
close all
clc
[FileName,PathName] = uigetfile('*.bin',...
    'Select *.bin File output by Insight3 ',...
    'MultiSelect', 'off');
cd(PathName);
Afname=char(FileName);
Molecule=ReadMasterMoleculeList(Afname);
width=Molecule.w;
height=Molecule.h;
plot(width,height,'*');
%% delete the bright tetraspeckbeads
frame_Value=input('Do you want to refine frame range ? Please input the max value to cut');
Moleculewithoutbeads=find(Molecule.frame<frame_Value);
plot(width(Moleculewithoutbeads,:),height(Moleculewithoutbeads,:),'*');
format = {...
    'single' [1 1] 'x'; ...
    'single' [1 1] 'y'; ...
    'single' [1 1] 'xc'; ...
    'single' [1 1] 'yc'; ...
    'single' [1 1] 'h'; ...
    'single' [1 1] 'a'; ...
    'single' [1 1] 'w'; ...
    'single' [1 1] 'phi'; ...
    'single' [1 1] 'ax'; ...
    'single' [1 1] 'bg'; ...
    'single' [1 1] 'i'; ...
    'int32' [1 1] 'c'; ...
    'int32' [1 1] 'density'; ...
    'int32' [1 1] 'frame'; ...
    'int32' [1 1] 'length'; ...
    'int32' [1 1] 'link'; ...
    'single' [1 1] 'z'; ...
    'single' [1 1] 'zc';};
for i=1:length(format)
     Molecule_deletebeads.(format{i,3})=Molecule.(format{i,3})(Moleculewithoutbeads,:);
end
WriteMoleculeList(Molecule_deletebeads,[FileName(1:end-9) '_frame.bin'])

