% Recaculate the sensory position of the not significantly aligned cells
clear;close all;clc;
folder_name=uigetdir('Please select the folder that contains all the .mat file generated by ALI_basalbody_analysis_Main');
cd(folder_name);
files = dir([folder_name '\*.tiff']);
if isempty(files)
    display('no files identified under the current folder')
end

for i=1:length(files)
    tiff_name=files(i).name;
    main_name=[files(i).name(1:end-5) '_main_information.mat'];
    if ~isempty(main_name)
    data=importdata(main_name);
    mean_direction=data.mean_direction;
    threshold=data.threshold;
    image=imread(tiff_name);
    red=image(:,:,1);
    index=find(red~=0);
    [I,J]=ind2sub(size(red),index);
    centroid=[mean(J),mean(I)];
    [x_distance_norm,y_distance_norm]=sensorycilia_position_func(tiff_name,90-(mean_direction/pi*180),centroid);
    end
    newdata=data;
    newdata.x_distance=x_distance_norm;
    newdata.y_distance=y_distance_norm;
    newcellname=[files(i).name(1:end-4)  '_main_information2.mat'];   
    save(newcellname,'newdata')
    clear tiff_name main_name data mean_direction threshold image red index I J centroid x_distance_norm y_distance_norm newdata newcellname
end