clear;close all;clc;
folder_name=uigetdir('Please select the folder that contains all the .mat file generated by ALI_basalbody_analysis_Main');
cd(folder_name);
files = dir([folder_name '\*_main_information.mat']);


if isempty(files)
    display('no files identified under the current folder')
end

all=[];
for i=1:length(files)
    data=importdata(files(i).name);
    p_value=data.p_value;
    mean_direction=data.mean_direction;
    all_directions=data.all_directions;
    bb_number=data.basalbody_number;
    if ~isempty(p_value);
    vector_len=circ_r(all_directions);
    if p_value<0.05
        k=1;
    else
        k=0;
    end    
    all=[all;i,k,p_value,mean_direction,bb_number,vector_len]; 
    end    
    
end
% the structure of all
% column 1: the index of the cell
% column 2: whether it is significantly aligned or not, 1 stands for aligned, 0 tands
% for not aligned
% column 3: p_value
% column 4: mean_direction
% column 5: bb_number
% column 6: vector_len
 index=find(all(:,2)==1);
 aligned_percentage=length(index)/length(all);
 [p_value_cell,z_value_cell]=circ_rtest(all(:,4));
 display(aligned_percentage);
 


  


