clear;close all;clc;
folder_name=uigetdir('Please select the folder that contains all the .mat file generated by cilia_direction_calculation_version2');
cd(folder_name);
files = dir([folder_name '\*_generateddata.mat']);
z=1;
if isempty(files)
    display('no files identified under the current folder')
end
figure1=figure(1);
title('Quantitative analysis of celluar orientation')
for i=1:length(files)
    data=importdata(files(i).name);
    direction=data.dp(:,6); % direction [-pi,pi]
    vector_length=circ_r(direction); 
    mean_direction=circ_mean(direction);
    [p_value,z_value]=circ_rtest(direction);
    save([files(i).name(1:end-4) '_generateddata2.mat']);
    x=vector_length*cos(mean_direction);
    y=vector_length*sin(mean_direction);
    if p_value<0.05
       polar(mean_direction,1,'bo')
       hold on
       compass(x,y,'b-')
    else
       polar(mean_direction,1,'ro')
       hold on
       compass(x,y,'r-')
    end
    hold on
    clear data direction vector_length mean_direction 
    clear p_value z_value
    clear x y
end
saveas(figure1,[folder_name '_cellulardirection.tif'],'tiffn');
saveas(figure1,[folder_name '_cellulardirection.fig'],'fig');

