% optimizing threshold for PCD diagnosis
folder_name=uigetdir('Please select the folder that contains all the .mat file generated by PCD_diagnosis_v4_freedraw_contrast_3D');
cd(folder_name);
files = dir([folder_name '\*_rawdata.mat']);
all=[];

allgreenintensity_wt=[];
allgreenintensity_p=[];

allredintensity_wt=[];
allredintensity_p=[];

for j=1:length(files)
    display('cell')
    display(num2str(j));
    display('in progress')
    data=importdata(files(j).name);
    k=strfind(files(j).name, 'WT');   
    for i=1:data.num_images/2
            red_temp=data.red_raw(:,:,i);
            green_temp=data.green_raw(:,:,i);                       
            if ~isempty(k)
              allgreenintensity_wt=[allgreenintensity_wt;green_temp(data.InboundaryIndexlist_green)];
              allredintensity_wt=[allredintensity_wt;red_temp(data.InboundaryIndexlist_red)];             
            else
              allgreenintensity_p=[allgreenintensity_p;green_temp(data.InboundaryIndexlist_green)];
              allredintensity_p=[allredintensity_p;red_temp(data.InboundaryIndexlist_red)];
            end        
    end        
  display('finished')
  clear data
end
display('All cell finished')
% check whether the data is wild type or patient

   