clear;close all;clc;
folder=uigetdir('Please select the folder that contains all the sensoryposition_generateddata.mat file generated by ALI_basalbody_analysis_Main');
cd(folder);
files = dir([folder '\*_sensoryposition_generateddata.mat']);
if isempty(files)
    display('no files identified under the current folder')
end
sensory_centroid_distance=[];
normalized_x=[];
normalized_y=[];
radius_all=[];
catch_sequence=[];
for i=1:length(files)
    try
    data=importdata(files(i).name);
    x_distance=data.x_distance(1);
    y_distance=data.y_distance(1);
    distance=(x_distance^2+y_distance^2)^0.5;
    sensory_centroid_distance=[sensory_centroid_distance;distance];
    x_distance_norm=data.x_distance_norm(1);
    y_distance_norm=data.y_distance(1)/data.heighth;
    normalized_x=[normalized_x;x_distance_norm];
    normalized_y=[normalized_y;y_distance_norm];
    width=data.width;
    height=data.heighth;
    radius=(width+height)/4;
    radius_all=[radius_all;radius];
    catch
     catch_sequence=[sequence;i];
   end   
end
outbounds=find(normalized_x<-0.5|normalized_y<-0.5|normalized_x>0.5|normalized_y>0.5);
normalized_x(outbounds)=[];
normalized_y(outbounds)=[];
sensory_centroid_distance(outbounds)=[];
radius_all(outbounds)=[];
normalized_sensory_centroid_distance=sensory_centroid_distance./radius_all;

