clear;close all;clc;
folder_name=uigetdir('Please select the folder that contains all the .mat file generated by ALI_basalbody_analysis_Main');
cd(folder_name);
files = dir([folder_name '\*_sensoryposition_generateddata.mat']);



z=1;
if isempty(files)
    display('no files identified under the current folder')
end
%figure1=figure(1);

sensoryy=[];
direction=[];
sequence=[];
sequence2=[];

vector_length=[];
cilia_number=[];
sensoryx=[];

for i=1:length(files)
    try
    data=importdata(files(i).name);
    name=files(i).name;
    name2=[files(i).name(1:end-33) 'directionfunction_generateddata.mat'];
    name3=[files(i).name(1:end-35) '_main_information.mat'];
    sequence=[sequence;i];
    data2=importdata(name2);
    data3=importdata(name3);
    cilia_number=[cilia_number;data3.basalbody_number];
    y_distance=data.sensory_y(1);
    y_max=data.bounding_y_max;
    y_min=data.bounding_y_min;
    range=y_max-y_min;
    y=y_distance-y_min; 
    normalizeddata=y/range;
    sensoryy=[sensoryy;normalizeddata];
    sensoryx=[sensoryx;data3.x_distance];
    final=data2.final;
    vector_len=circ_r(final(:,1));
    vector_length=[vector_length;vector_len]; 
    catch
     sequence2=[sequence2;i];
    end
    
end
index=find(cilia_number>400);
cilia_number(index)=[];
vector_length(index)=[];
sensoryy(index)=[];
% figure display
hist(sensoryy,0:0.1:1)
title('Sensory cilia position show localization bias')
xlabel('Distance to the flow direction normalized by the cell length along the cell')
ylabel('Cell counts')
figure
scatter(vector_length,sensoryy)
xlabel('vector length')
ylabel('sensoryy relative position')
title('Sensory cilia position as a function of vector length')
[R,P] = corrcoef(vector_length,sensoryy);
figure
hist(sensoryx,-0.6:0.1:0.6)
title('Sensory cilia position distribution perpendicular to the flow')
xlabel('Distance to the center normalized by the cell width')
ylabel('Cell counts')


