%% Scriptstopullhisdata
%% Sun Moon
%% Extarct data from figure meanspeed distribution generated by BiFC_PALM_SMT_V4
figure(1);
subplot(1,3,2);
bifc=get(gca);
b2=bifc.Children;
b2=get(bifc.Children);
BiFCXdata=b2.XData;
BiFCYdata=b2.YData;
Xedge=BiFCXdata(3,:);
Y=BiFCYdata(3,:);
Xedge=[BiFCXdata(1,1) Xedge];
X1=Xedge(1:end-1);
X2=Xedge(2:end);
X=(X1+X2)/2;
MeanspeedHistdata=[X;Y];
csvwrite('MeanspeedHistdata.xls',MeanspeedHistdata);