clear;
close all;
clc;
folder_name=uigetdir('Please select the folder that contains all the .mat file generated by ALI_basalbody_analysis_Main');
cd(folder_name);
files = dir([folder_name '\*_main_information.mat']);
if isempty(files)
    display('no files identified under the current folder')
end
all=[];
for i=1:length(files)
    data=importdata(files(i).name);
    p_value=data.p_value;
    all_directions=data.all_directions;
    if ~isempty(p_value);
        vector_len=circ_r(all_directions);
        bb_number=data.basalbody_number;
        if p_value<0.05
            k=1;
        else
            k=0;
        end    
        all=[all;i,k,p_value,vector_len,bb_number]; 
    end        
end
% The structure of all
 % column 1: the index of the cell
 % column 2: whether it is significantly aligned or not, 1 stands for aligned, 0 stands
 % for not aligned
 % column 3: p_value
 % column 4: vector_len_afterrefine??
 % column 5: bb_number
 
bb_index=find(all(:,5)>=120&all(:,5)<=300); % erase some obvious mistakes
all=all(bb_index,:);
alignedcell_number=length(find(all(:,2)==1));
allcell_number=length(all);
alignedpercentage=alignedcell_number/allcell_number;
display(alignedpercentage);
display('cell number');
display(length(all));
 


  


