%get the basal body number and std
clear;close all;clc;
folder_name=uigetdir('Please select the folder that contains all the .mat file generated by ALI_basalbody_analysis_Main');
cd(folder_name);
files = dir([folder_name '\*_main_information.mat']);
if isempty(files)
    display('no files identified under the current folder')
end
bball=[];
thresholdall=[];
for i=1:length(files)
    data=importdata(files(i).name);
    bbnumber=data.basalbody_number;
    threshold=data.threshold;
    bball=[bball;bbnumber];  
    thresholdall=[thresholdall;threshold];
end

%bbmean=mean(bball(bball(:,1)<=350&bball(:,1)>=100));
%bbstd=std(bball(bball<=350&bball>=100));

bbmean=mean(bball(bball(:,1)<=350));
bbstd=std(bball(bball<=350));





display('basal body number')
display(bbmean)
display('basal body number std')
display(bbstd)
bball_thresholdall=[bball,thresholdall];
display('counts');
%display(length(bball(bball<=350&bball>=100)));
display(length(bball(bball<=350)));
display('threshold');
display(mean(thresholdall));